resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/anishvk/cons-test.git
    branch: master

- name: cf-cli
  type: cf-cli-resource
  source:
    api: https://api.mvtest-harbor.live
    username: admin
    password: g0mw39bahwle1qjdlqgv
    org: dev
    space: dec-space

jobs:
- name: build-and-deploy
  public: true
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: "3-jdk-8-slim"
      inputs:
      - name: git-repo
      outputs:
      - name: app
      run:
        path: sh
        args:
        - -exc
        - |
          cd git-repo/
          mvn clean package -DskipTests
          cp target/sample-maven-webapp.war ../app/sample-maven-webapp.war
  - put: cf-cli
    params:
      command: push
      manifest: git-repo/manifest.yml
      path: app/sample-maven-webapp.war
